### ISSUE TITLE
Issue/Feature: Parsing Outputs from Terraform to Inspec Control Test

### ISSUE THREAD

**Issue by yobooooi** [joatmon08/tdd-infrastructure#2]
Hey Rosemary,

This was really awesome. Thanks for the code, it really helped me get started with both Conftest and Kitchen Terraform. Something I was having issues with is parsing the outputs from Terraform as inputs or attributes to one of my control tests. Is this perhaps something you've managed to get working yet ? Or would you recomend just creating these tests using the terraform templates module ?

```ruby
instance_id = attribute('instance_id')
control "instance_state" do
title "Checks the instance state from SSM"

describe command("aws ssm describe-instance-information --filters \"Key=InstanceIds,Values=#{instance_id['value']}\" --profile internal-dev --region eu-west-1  | jq -r '.[][].PingStatus'") do
     its('stdout') { should match "Online" }
   end
end
```

**Comment by joatmon08** [comment]
Hello Adan!

I haven't reliably parsed outputs into the control tests either, I suspect it has something to do with some kind of output capture issue. I think the use of terraform templates could be really interesting, although I would be hesitant about how they get updated if I want to add a new test.

I've used `terraform output -json` and then read the JSON values from that into the control tests in the past and it works reliably enough, although the workflow is a little inefficient since I have to retrieve the outputs from there.

It's been some time since your question, I'd be curious if you figured out how to get it working and how you approached the problem!

Rosemary

**Comment by yobooooi** [comment]
Hey Rosemary,

Thank you for responding. Yeah you make a very good point, making use of templates for tests would blur the lines between what is a test vs what is part of the code base. 

Thanks for the heads up with making use of  `terraform output -json` will definitely check it out. But if I'm being honest, my development environment broke and also the `cdkft` is keeping me quite busy :) its so fun. If I come up with something, I'd definitely reach out.

Also, I really admire your contribution and talks to the broader community. Its so interesting, and your style of teaching makes learning new things so approachable. For someone wanting to contribute, do you have any parting advice :) ?

**Comment by yobooooi** [comment]
Its been a while. I just haven't had the time to check out testing terraform in such a while. I played around with Terratest, and its alot more reliable with getting output values from the terraform code. And they also have a ton of built in methods for specific AWS, Azure or GCP resources as well as an HTTP helper and a Shell library. Its quite rudimentary but it has enough to cover a broad range of tests. 

The example below, gets all instances from an ASG and iterates through the response to check if they're managed by SSM. 

```go
package test

import (
	"time"
	"fmt"
	"testing"
	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/terraform"
)

var aws_region string  = "eu-west-1"

func TestTerraformAWSLaunchConfigSSMManagedInstance(t *testing.T) {
	terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		TerraformDir: "../dev/",
		TerraformBinary: "terraform",
		VarFiles: []string{"../dev/tests/vars.tfvars"},
		EnvVars: map[string]string{"TF_LOG":"ERROR"},
	})
	// instead of Terraform applying for each test, the output can just be consulted to get the output values for any
	// subsequent tests that need to be run

	// terraform.Apply(t, terraformOptions)
	// defer terraform.Destroy(t, terraformOptions)

	aws_asg_name := terraform.Output(t, terraformOptions, "wordpress_asg_name")
	instance_ids := aws.GetInstanceIdsForAsg(t, aws_asg_name, aws_region)
	fmt.Printf("Autoscaling Group Name:\t%s\n", aws_asg_name)
	fmt.Printf("InstanceIds:\t%s\n", instance_ids)
	
	wait_period, _  := time.ParseDuration("1m30s")
	for _, instance := range instance_ids {
		aws.WaitForSsmInstance(t, aws_region, instance, wait_period)
	}
	
}
```

Check out my repository if you ever interested. Its still a WIP, but wanting to get it to a point where it builds infrastructure for a typical wordpress implementation. 

https://github.com/yobooooi/infrastructure-modules-ec2
